project1: project1.c
	gcc project1.c -o bin/project1
clean:
	rm $(shell pwd)/dir1/file3.txt
	rm $(shell pwd)/dir1/file4.txt
	rm $(shell pwd)/dir2/file1.txt
	rm $(shell pwd)/dir2/file2.txt
	rm $(shell pwd)/bin/project1

